// redux actions
const LOGIN_NEW_TOKEN_REQUEST = 'LOGIN_NEW_TOKEN_REQUEST';
const LOGIN_NEW_TOKEN_REQUEST_SUCCESS = 'LOGIN_NEW_TOKEN_REQUEST_SUCCESS';
const LOGIN_NEW_TOKEN_REQUEST_FAILURE = 'LOGIN_NEW_TOKEN_REQUEST_FAILURE';

const LOGIN_NEW_SESSION_REQUEST = 'LOGIN_NEW_SESSION_REQUEST';
const LOGIN_NEW_SESSION_REQUEST_SUCCESS = 'LOGIN_NEW_SESSION_REQUEST_SUCCESS';
const LOGIN_NEW_SESSION_REQUEST_FAILURE = 'LOGIN_NEW_TOKEN_REQUEST_FAILURE';

const LOGIN_DELETE_SESSION_REQUEST = 'LOGIN_DELETE_SESSION_REQUEST';
const LOGIN_DELETE_SESSION_REQUEST_SUCCESS = 'LOGIN_DELETE_SESSION_REQUEST_SUCCESS';
const LOGIN_DELETE_SESSION_REQUEST_FAILURE = 'LOGIN_DELETE_SESSION_REQUEST_FAILURE';

const LoginActionTypes = {
  LOGIN_NEW_TOKEN_REQUEST,
  LOGIN_NEW_TOKEN_REQUEST_SUCCESS,
  LOGIN_NEW_TOKEN_REQUEST_FAILURE,

  LOGIN_NEW_SESSION_REQUEST,
  LOGIN_NEW_SESSION_REQUEST_SUCCESS,
  LOGIN_NEW_SESSION_REQUEST_FAILURE,

  LOGIN_DELETE_SESSION_REQUEST,
  LOGIN_DELETE_SESSION_REQUEST_SUCCESS,
  LOGIN_DELETE_SESSION_REQUEST_FAILURE,
};

export default LoginActionTypes;
