// redux actions
const SEARCH_MULTI_REQUEST = 'SEARCH_MULTI_REQUEST';
const SEARCH_MULTI_REQUEST_SUCCESS = 'SEARCH_MULTI_REQUEST_SUCCESS';
const SEARCH_MULTI_REQUEST_FAILURE = 'SEARCH_MULTI_REQUEST_FAILURE';

const SearchActionTypes = {
  SEARCH_MULTI_REQUEST,
  SEARCH_MULTI_REQUEST_SUCCESS,
  SEARCH_MULTI_REQUEST_FAILURE,
};

export default SearchActionTypes;
