// redux actions
const TV_AIRING_TODAY_REQUEST = 'TV_AIRING_TODAY_REQUEST';
const TV_AIRING_TODAY_REQUEST_SUCCESS = 'TV_AIRING_TODAY_REQUEST_SUCCESS';
const TV_AIRING_TODAY_REQUEST_FAILURE = 'TV_AIRING_TODAY_REQUEST_FAILURE';

const TV_DETAILS_REQUEST = 'TV_DETAILS_REQUEST';
const TV_DETAILS_REQUEST_SUCCESS = 'TV_DETAILS_REQUEST_SUCCESS';
const TV_DETAILS_REQUEST_FAILURE = 'TV_DETAILS_REQUEST_FAILURE';

const TV_ON_THE_AIR_REQUEST = 'TV_ON_THE_AIR_REQUEST';
const TV_ON_THE_AIR_REQUEST_SUCCESS = 'TV_ON_THE_AIR_REQUEST_SUCCESS';
const TV_ON_THE_AIR_REQUEST_FAILURE = 'TV_ON_THE_AIR_REQUEST_FAILURE';

const TV_POPULAR_REQUEST = 'TV_POPULAR_REQUEST';
const TV_POPULAR_REQUEST_SUCCESS = 'TV_POPULAR_REQUEST_SUCCESS';
const TV_POPULAR_REQUEST_FAILURE = 'TV_POPULAR_REQUEST_FAILURE';

const TV_TOP_RATED_REQUEST = 'TV_TOP_RATED_REQUEST';
const TV_TOP_RATED_REQUEST_SUCCESS = 'TV_TOP_RATED_REQUEST_SUCCESS';
const TV_TOP_RATED_REQUEST_FAILURE = 'TV_TOP_RATED_REQUEST_FAILURE';

const MovieActionTypes = {
  TV_AIRING_TODAY_REQUEST,
  TV_AIRING_TODAY_REQUEST_SUCCESS,
  TV_AIRING_TODAY_REQUEST_FAILURE,

  TV_DETAILS_REQUEST,
  TV_DETAILS_REQUEST_SUCCESS,
  TV_DETAILS_REQUEST_FAILURE,

  TV_ON_THE_AIR_REQUEST,
  TV_ON_THE_AIR_REQUEST_SUCCESS,
  TV_ON_THE_AIR_REQUEST_FAILURE,

  TV_POPULAR_REQUEST,
  TV_POPULAR_REQUEST_SUCCESS,
  TV_POPULAR_REQUEST_FAILURE,

  TV_TOP_RATED_REQUEST,
  TV_TOP_RATED_REQUEST_SUCCESS,
  TV_TOP_RATED_REQUEST_FAILURE,
};

export default MovieActionTypes;
