// redux actions
const MOVIE_DETAILS_REQUEST = 'MOVIE_DETAILS_REQUEST';
const MOVIE_DETAILS_REQUEST_SUCCESS = 'MOVIE_DETAILS_REQUEST_SUCCESS';
const MOVIE_DETAILS_REQUEST_FAILURE = 'MOVIE_DETAILS_REQUEST_FAILURE';

const MOVIE_NOW_PLAYING_REQUEST = 'MOVIE_NOW_PLAYING_REQUEST';
const MOVIE_NOW_PLAYING_REQUEST_SUCCESS = 'MOVIE_NOW_PLAYING_REQUEST_SUCCESS';
const MOVIE_NOW_PLAYING_REQUEST_FAILURE = 'MOVIE_NOW_PLAYING_REQUEST_FAILURE';

const MOVIE_POPULAR_REQUEST = 'MOVIE_POPULAR_REQUEST';
const MOVIE_POPULAR_REQUEST_SUCCESS = 'MOVIE_POPULAR_REQUEST_SUCCESS';
const MOVIE_POPULAR_REQUEST_FAILURE = 'MOVIE_POPULAR_REQUEST_FAILURE';

const MOVIE_TOP_RATED_REQUEST = 'MOVIE_TOP_RATED_REQUEST';
const MOVIE_TOP_RATED_REQUEST_SUCCESS = 'MOVIE_TOP_RATED_REQUEST_SUCCESS';
const MOVIE_TOP_RATED_REQUEST_FAILURE = 'MOVIE_TOP_RATED_REQUEST_FAILURE';

const MOVIE_UPCOMING_REQUEST = 'MOVIE_UPCOMING_REQUEST';
const MOVIE_UPCOMING_REQUEST_SUCCESS = 'MOVIE_UPCOMING_REQUEST_SUCCESS';
const MOVIE_UPCOMING_REQUEST_FAILURE = 'MOVIE_UPCOMING_REQUEST_FAILURE';

const MovieActionTypes = {
  MOVIE_DETAILS_REQUEST,
  MOVIE_DETAILS_REQUEST_SUCCESS,
  MOVIE_DETAILS_REQUEST_FAILURE,

  MOVIE_NOW_PLAYING_REQUEST,
  MOVIE_NOW_PLAYING_REQUEST_SUCCESS,
  MOVIE_NOW_PLAYING_REQUEST_FAILURE,

  MOVIE_POPULAR_REQUEST,
  MOVIE_POPULAR_REQUEST_SUCCESS,
  MOVIE_POPULAR_REQUEST_FAILURE,

  MOVIE_TOP_RATED_REQUEST,
  MOVIE_TOP_RATED_REQUEST_SUCCESS,
  MOVIE_TOP_RATED_REQUEST_FAILURE,

  MOVIE_UPCOMING_REQUEST,
  MOVIE_UPCOMING_REQUEST_SUCCESS,
  MOVIE_UPCOMING_REQUEST_FAILURE,
};

export default MovieActionTypes;
