// redux actions
const ACCOUNT_DETAILS_REQUEST = 'ACCOUNT_DETAILS_REQUEST';
const ACCOUNT_DETAILS_REQUEST_SUCCESS = 'ACCOUNT_DETAILS_REQUEST_SUCCESS';
const ACCOUNT_DETAILS_REQUEST_FAILURE = 'ACCOUNT_DETAILS_REQUEST_FAILURE';

const AccountActionTypes = {
  ACCOUNT_DETAILS_REQUEST,
  ACCOUNT_DETAILS_REQUEST_SUCCESS,
  ACCOUNT_DETAILS_REQUEST_FAILURE,
};

export default AccountActionTypes;
