// redux actions
const ACCOUNT_DETAILS_REQUEST = 'ACCOUNT_DETAILS_REQUEST';
const ACCOUNT_DETAILS_REQUEST_SUCCESS = 'ACCOUNT_DETAILS_REQUEST_SUCCESS';
const ACCOUNT_DETAILS_REQUEST_FAILURE = 'ACCOUNT_DETAILS_REQUEST_FAILURE';

const ACCOUNT_FAVORITE_MOVIES_REQUEST = 'ACCOUNT_FAVORITE_MOVIES_REQUEST';
const ACCOUNT_FAVORITE_MOVIES_REQUEST_SUCCESS = 'ACCOUNT_FAVORITE_MOVIES_REQUEST_SUCCESS';
const ACCOUNT_FAVORITE_MOVIES_REQUEST_FAILURE = 'ACCOUNT_FAVORITE_MOVIES_REQUEST_FAILURE';

const ACCOUNT_FAVORITE_TV_REQUEST = 'ACCOUNT_FAVORITE_TV_REQUEST';
const ACCOUNT_FAVORITE_TV_REQUEST_SUCCESS = 'ACCOUNT_FAVORITE_TV_REQUEST_SUCCESS';
const ACCOUNT_FAVORITE_TV_REQUEST_FAILURE = 'ACCOUNT_FAVORITE_TV_REQUEST_FAILURE';

const ACCOUNT_WATCHLIST_MOVIES_REQUEST = 'ACCOUNT_WATCHLIST_MOVIES_REQUEST';
const ACCOUNT_WATCHLIST_MOVIES_REQUEST_SUCCESS = 'ACCOUNT_WATCHLIST_MOVIES_REQUEST_SUCCESS';
const ACCOUNT_WATCHLIST_MOVIES_REQUEST_FAILURE = 'ACCOUNT_WATCHLIST_MOVIES_REQUEST_FAILURE';

const ACCOUNT_WATCHLIST_TV_REQUEST = 'ACCOUNT_WATCHLIST_TV_REQUEST';
const ACCOUNT_WATCHLIST_TV_REQUEST_SUCCESS = 'ACCOUNT_WATCHLIST_TV_REQUEST_SUCCESS';
const ACCOUNT_WATCHLIST_TV_REQUEST_FAILURE = 'ACCOUNT_WATCHLIST_TV_REQUEST_FAILURE';

const AccountActionTypes = {
  ACCOUNT_DETAILS_REQUEST,
  ACCOUNT_DETAILS_REQUEST_SUCCESS,
  ACCOUNT_DETAILS_REQUEST_FAILURE,

  ACCOUNT_FAVORITE_MOVIES_REQUEST,
  ACCOUNT_FAVORITE_MOVIES_REQUEST_SUCCESS,
  ACCOUNT_FAVORITE_MOVIES_REQUEST_FAILURE,

  ACCOUNT_FAVORITE_TV_REQUEST,
  ACCOUNT_FAVORITE_TV_REQUEST_SUCCESS,
  ACCOUNT_FAVORITE_TV_REQUEST_FAILURE,

  ACCOUNT_WATCHLIST_MOVIES_REQUEST,
  ACCOUNT_WATCHLIST_MOVIES_REQUEST_SUCCESS,
  ACCOUNT_WATCHLIST_MOVIES_REQUEST_FAILURE,

  ACCOUNT_WATCHLIST_TV_REQUEST,
  ACCOUNT_WATCHLIST_TV_REQUEST_SUCCESS,
  ACCOUNT_WATCHLIST_TV_REQUEST_FAILURE,
};

export default AccountActionTypes;
