// redux actions
const PERSON_COMBINED_CREDITS_REQUEST = 'PERSON_COMBINED_CREDITS_REQUEST';
const PERSON_COMBINED_CREDITS_REQUEST_SUCCESS = 'PERSON_COMBINED_CREDITS_REQUEST_SUCCESS';
const PERSON_COMBINED_CREDITS_REQUEST_FAILURE = 'PERSON_COMBINED_CREDITS_REQUEST_FAILURE';

const PERSON_DETAILS_REQUEST = 'PERSON_DETAILS_REQUEST';
const PERSON_DETAILS_REQUEST_SUCCESS = 'PERSON_DETAILS_REQUEST_SUCCESS';
const PERSON_DETAILS_REQUEST_FAILURE = 'PERSON_DETAILS_REQUEST_FAILURE';

const PERSON_POPULAR_REQUEST = 'PERSON_POPULAR_REQUEST';
const PERSON_POPULAR_REQUEST_SUCCESS = 'PERSON_POPULAR_REQUEST_SUCCESS';
const PERSON_POPULAR_REQUEST_FAILURE = 'PERSON_POPULAR_REQUEST_FAILURE';

const PersonActionTypes = {
  PERSON_COMBINED_CREDITS_REQUEST,
  PERSON_COMBINED_CREDITS_REQUEST_SUCCESS,
  PERSON_COMBINED_CREDITS_REQUEST_FAILURE,

  PERSON_DETAILS_REQUEST,
  PERSON_DETAILS_REQUEST_SUCCESS,
  PERSON_DETAILS_REQUEST_FAILURE,

  PERSON_POPULAR_REQUEST,
  PERSON_POPULAR_REQUEST_SUCCESS,
  PERSON_POPULAR_REQUEST_FAILURE,
};

export default PersonActionTypes;
